### ISSUE TITLE
Add weather API key to settings

### ISSUE THREAD

**Issue by beroset** [dodoradio/Buran#19]
The current weather API key is hardcoded, but it should be settable by the user with the current value as a default.

**Comment by dodoradio** [comment]
I will add another field to settings for this

**Comment by beroset** [comment]
I've updated the code that uses the apikey so that it now expects the settings to contain a string "apikey" under the category of "Weather".  If the settings field uses the same location, that would be perfect.  We can also use the original hardcoded value as a default; I created it for this application.
